# Generated by Django 5.1.6 on 2025-02-23 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0002_battery_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battery',
            name='test_field',
        ),
    ]
