# Generated by Django 4.2.20 on 2025-03-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0001_squashed_0003_remove_battery_test_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
