# Generated by Django 4.2.20 on 2025-04-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0005_warehousea_warehouseb_warehousec_delete_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='battery',
            name='image',
            field=models.ImageField(upload_to='inventory/images/'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
