# Generated by Django 5.1.7 on 2025-03-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('serial_num', models.IntegerField(primary_key=True, serialize=False)),
                ('part_num', models.IntegerField()),
                ('item_type', models.CharField(max_length=60)),
                ('user_ID', models.CharField(max_length=80)),
                ('location', models.CharField(max_length=80)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('madlibs', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
